### PR TITLE
All files upload and routing between pages

### PR DESCRIPTION
**Pull request by mtolrom**
Changes

01- add book with cover_image and redirect to book page
02- Go from BookList to 1 book page
03- Add picture and redirect to book page
04- add page and redirect to language page
05- add language and redirect to Text and Audio upload page
06- Add Text file and redirect to language page
07- Add audio file and redirect to language page
08- list pages
09- List languages

### CODE REVIEW

**Review by jameriah30 — APPROVED** [review]
Looks good. I

**Comment by ncobb01** [comment]
Approved

**Comment by ncobb01** [comment]
Attempt 2

**Review by HjLubas — APPROVED** [review]
Good for me!

**Comment by DnlBell** [comment]
there are no conflicts, but you should be removing the text lines you have for testing before we merge stuff into develop

**Pull request merged**
