### PR TITLE
Jerbranch

### PR DESCRIPTION
**Pull request by jameriah30**
This is the initial pull request with everything I did for sprint 2. I've integrated my index.html(Admin Portal Page) along with 2 js files into the new dev branch. As soon as this is merged, I will refactor my file and component structure and begin to integrate the login and add book pages into what I have.

### CODE REVIEW

**Comment by DnlBell** [comment]
You need to have your code encapsulated as a Component .vue file and then add it to the avalible components in the app.vue file. **Do Not** edit index.js

**Comment by DnlBell** [comment]
leave index.html as it is currently in the develop branch

**Review by DnlBell — CHANGES_REQUESTED** [review]
You need to have your code encapsulated as a Component .vue file and then add it to the avalible components in the app.vue file. **Do Not** edit index.js as it is in the develop branch

**Comment by jameriah30** [comment]
I understand breaking up functions into components, but I'm not quite sure how to go about doing that with mine since it is the primary homepage(index), that contains the design of the ui and has a fair amount of html/bootstrap. I'm looking into that now. Should I be breaking the sections(elements) of the page into individual components? Or can this all fit into one? Sorry for my confusion, but this is my first time using Vue...

**Comment by DnlBell** [comment]
You need to do more research into vue I can't tell you everything. But if you look at how the index file is setup now it will mount the app.vue component and nothing else. If you go to the app.vue file you will see components that are avalible to it. As far as getting it to be the "Home" page you and your team need to look into implementing some routing.

# Docs:

## components  
https://vuejs.org/v2/guide/components.html
https://vuejs.org/v2/guide/components-registration.html

## routing 
https://router.vuejs.org/guide/#html

**Comment by jameriah30** [comment]
Gotcha. I certainly don't expect to to tell me everything. Was just trying to get a sense of what you're looking for. Thanks for the info.

**Pull request closed without merging**
