### PR TITLE
Jeremiahbranch

### PR DESCRIPTION
**Pull request by jameriah30**
Added the new components for the new work flow of Adding a new book and add content for a book. Deleted the older components of the previous work flow that are not being used.

### CODE REVIEW

**Review by HjLubas — DISMISSED** [review]
Good to go!

**Comment by mtolrom** [comment]
Approved

**Review by mtolrom — APPROVED** [review]
Good to go! Thanks.

**Comment by DnlBell** [comment]
Looks good to me

**Review by DnlBell — APPROVED** [review]
Looks to be working

**Pull request merged**
