### PR TITLE
pull dev into master

### PR DESCRIPTION
**Pull request by gshields5541**

### CODE REVIEW

**Review by DnlBell — DISMISSED** [review]

**Comment by DnlBell** [comment]
This is a pull request from dev into master.  If you have code to add from your own branch create a pull request from there to dev. I am going to approve this merge however, since we need to test the production pipeline.

**Review by jameriah30 — DISMISSED** [review]
Approved

**Review by DnlBell — APPROVED** [review]
looks like the update from master didn't break anything

**Review by D3v0nM — APPROVED** [review]
Rubber stamp

**Pull request merged**
